### ISSUE TITLE
Return code of i2b & b2i functions is not zero

### ISSUE THREAD

**Issue by purpleskyfall** [1acheng/INX_Editor#1]
使用 `inx i2b` 或 `inx b2i` 功能转换 IONEX 文件时，运行成功之后是否应该返回 0？其他功能如 `inx tec` 或者 `inx edit` 皆在运行成功后返回 0。

示例：

```
$ inx b2i --input input_files/whug1280.dat --output temp/whug1280.17i
```

**Comment by 1acheng** [comment]
谢谢！已修复。请下载新版V1.2 。 @purpleskyfall
